=== Jeroen-N/Facturatie/XML/ClientFormat.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Clienten">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Client" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ClientGegevens">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Naam"/>
                    <xs:element type="xs:string" name="Adres"/>
                    <xs:element type="xs:string" name="Postcode"/>
                    <xs:element type="xs:string" name="Woonplaats"/>
                    <xs:element type="xs:string" name="Geboortedatum"/>
                    <xs:element type="xs:int" name="Telefoonnummer"/>
                    <xs:element type="xs:string" name="Email"/>
                    <xs:element type="xs:string" name="BetaalMethode"/>
                    <xs:element type="xs:string" name="ResterendEigenRisico"/>
                    <xs:element type="xs:string" name="Rekeningnummer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="VerzekeringPolis">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="VerzekeringType"/>
                    <xs:element type="xs:float" name="EigenRisico"/>
                    <xs:element type="xs:string" name="startDatum"/>
                    <xs:element type="xs:string" name="eindDatum"/>
                  </xs:sequence>
                  <xs:attribute type="xs:int" name="PolisNummer"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="facturen">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="factuur" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="factuurDatum"/>
                          <xs:element type="xs:string" name="vervalDatum"/>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="factuurNummer"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Behandelingen">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Behandeling" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="behandelgegevens">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:int" name="Fysiotherapeut"/>
                                <xs:element type="xs:int" name="Behandelcode"/>
                                <xs:element type="xs:int" name="fysioPraktijkNummer"/>
                                <xs:element type="xs:string" name="BehandelStartDatum"/>
                                <xs:element type="xs:string" name="BehandelEindDatum"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="behandelafspraak" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:int" name="Sessie"/>
                                <xs:element type="xs:string" name="Status"/>
                                <xs:element type="xs:string" name="Datum"/>
                                <xs:element type="xs:string" name="Begintijd"/>
                                <xs:element type="xs:string" name="Eindtijd"/>
                                <xs:element type="xs:int" name="Praktijkruimte"/>
                                <xs:element type="xs:string" name="Opmerking"/>
                              </xs:sequence>
                              <xs:attribute type="xs:int" name="ID"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="id"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Diagnoses">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Diagnose">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Behandelcodes">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Behandelcode" maxOccurs="unbounded" minOccurs="0">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:int">
                                        <xs:attribute type="xs:int" name="id"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="Datum"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="BSN"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jeroen-N/Facturatie/FacturatieSysteem/XML/ClientFormat.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Clienten xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClientFormat.xsd">

	<Client BSN="125651201">
		<ClientGegevens>
			<Naam>Xander Gerreman</Naam>
			<Adres>Marialaan 9a</Adres>
			<Postcode>4834VG</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>10-06-1994</Geboortedatum>
			<Telefoonnummer>0682739024</Telefoonnummer>
			<Email>xpjgerre@avans.nl</Email>
			<BetaalMethode>incasso</BetaalMethode>
			<ResterendEigenRisico>0.0</ResterendEigenRisico>
			<Rekeningnummer>NL47RABO0136052159</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="87JH9G">
				<VerzekeringType>Kaas_Basic</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>01-01-2013</startDatum>
				<eindDatum>31-12-2013</eindDatum>
			</VerzekeringPolis>
		
			<VerzekeringPolis PolisNummer="BDVJLX">
				<VerzekeringType>Kaas_Basic</VerzekeringType>
				<EigenRisico>250.0</EigenRisico>
				<startDatum>10-06-2001</startDatum>
				<eindDatum>10-06-2002</eindDatum>
			</VerzekeringPolis></VerzekeringPolissen>
		<Facturen><Factuur FactuurNummer="1"><FactuurDatum>05-11-2014</FactuurDatum><VervalDatum>19-11-2014</VervalDatum><FactuurBehandelingen><FactuurBehandeling BehandelingID="12"><BehandelafspraakID>1847</BehandelafspraakID></FactuurBehandeling></FactuurBehandelingen><TevergoedenBedrag>150.0</TevergoedenBedrag><Status>Niet betaald</Status><Totaalprijs>0.0</Totaalprijs></Factuur></Facturen>
	</Client>
	<Client BSN="125651202">
		<ClientGegevens>
			<Naam>Sander Blijlevens</Naam>
			<Adres>Schijfstraat 26B</Adres>
			<Postcode>4847SM</Postcode>
			<Woonplaats>Breda</Woonplaats>
			<Geboortedatum>31-12-1995</Geboortedatum>
			<Telefoonnummer>0625235100</Telefoonnummer>
			<Email>sjmblijl@avans.nl</Email>
			<BetaalMethode>incasso</BetaalMethode>
			<ResterendEigenRisico>0.0</ResterendEigenRisico>
			<Rekeningnummer>NL47RABO0136052185</Rekeningnummer>
		</ClientGegevens>
		<VerzekeringPolissen>
			<VerzekeringPolis PolisNummer="KJ8JUY">
				<VerzekeringType>Kaas_Basic</VerzekeringType>
				<EigenRisico>200.0</EigenRisico>
				<startDatum>01-01-2013</startDatum>
				<eindDatum>31-12-2013</eindDatum>
			</VerzekeringPolis>
			<VerzekeringPolis PolisNummer="123456">
				<VerzekeringType>Kaas_Basic</VerzekeringType>
				<EigenRisico>1125.48</EigenRisico>
				<startDatum>01-01-2010</startDatum>
				<eindDatum>31-12-2011</eindDatum>
			</VerzekeringPolis>
			<VerzekeringPolis PolisNummer="BJOWB2">
				<VerzekeringType>Kaas_All-risk</VerzekeringType>
				<EigenRisico>250.0</EigenRisico>
				<startDatum>01-01-2015</startDatum>
				<eindDatum>01-01-2016</eindDatum>
			</VerzekeringPolis>
			<VerzekeringPolis PolisNummer="0GUNC4">
				<VerzekeringType>Kaas_All-risk</VerzekeringType>
				<EigenRisico>250.0</EigenRisico>
				<startDatum>03-11-2014</startDatum>
				<eindDatum>05-12-2015</eindDatum>
			</VerzekeringPolis></VerzekeringPolissen>
		<Facturen/>
	</Client>
</Clienten>
